apiVersion: stunner.l7mp.io/v1
kind: Dataplane
metadata:
  name: default
spec:
  replicas: 1
  resources:
    limits:
      cpu: 250m
      memory: 120Mi
    requests:
      cpu: 250m
      memory: 120Mi
  terminationGracePeriodSeconds: 60
  enableMetricsEndpoint: true
