apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: udproute-sample
  namespace: stunner
spec:
  parentRefs:
    - name: gateway-sample
      sectionName: sample-listener-udp
    - name: gateway-sample
      sectionName: sample-listener-tcp
  rules:
    - backendRefs:
        - name: udp-echo
          namespace: stunner
